### ISSUE TITLE
Possible to create gzip sitemaps? 

### ISSUE THREAD

**Issue by Samarpitr** [algolia/algolia-sitemap#13]
Can the files be gziped when generated?

**Comment by Haroenv** [comment]
Hey Samarpit, that is a great idea, thanks for the suggestion. You can always gzip the files yourself after generating them, but this seems like a good idea for the library itself! If you want to do it, feel free to suggest a pull request!

**Comment by vvo** [comment]
I feel like gzip is easier when handled by web servers, what is your underlying need/struggle @Samarpitr? The one that led you to create this issue, I am curious.

Thanks!

**Comment by harshmaur** [comment]
@Haroenv @vvo I gave the idea to @Samarpitr about the sitemaps. 

So basically I will tell you what is the case with eCommerce websites. 
There could be a huge catalog, like we have, around 10M records or more. all the links cannot be included in one sitemap, and I saw that there were batches of sitemaps created for it. 

Google or any other crawlers are built in to handle gz files since gz is quite small and the download is small. 

Along with gzip, I also want an index of sitemap is created that links all the batches. 

An example is this one https://www.compareraja.in/sitemap-index.xml
If you notice, the links are sitemaps links and they further link to more sitemaps, kind of creating a directory!! 

Now we also have the category name inside every product we have, I feel an awesome sitemap can be created if we can do all the links category wise and batch them. 

Let me know if you need more clarification on the same.

**Comment by harshmaur** [comment]
My idea is to run this sitemap script when there are major changes to my index and it automatically generates the folder with the sitemaps, which later I can upload to my webserver. The crawler will then automatically notice and start crawling.

**Comment by Haroenv** [comment]
This script already outputs up to 50000 links in 50000 sitemaps, which is 2.5 billion sitemaps in one sitemap index. This still needs to be mentioned in the documentation.

**Comment by harshmaur** [comment]
@Haroenv I see that the script only batches and it does not create an index of the batch, I think this feature is really required because the whole folder could be very dynamic.

**Comment by harshmaur** [comment]
@Haroenv if you think there is a possibility, I will try to make a PR for it.

**Comment by Haroenv** [comment]
It makes an index already @harshmaur, see https://yarnpkg.com/sitemaps/sitemap-index.xml for example, the sitemap index is being generated in 

https://github.com/algolia/algolia-sitemap/blob/master/index.js#L57-L58

**Comment by harshmaur** [comment]
Oh okay, We found that the script failed somewhere. @Samarpitr will get back to you on this

**Comment by Haroenv** [comment]
Sure, don’t hesitate to let me know when and where it breaks

**Comment by hotsprice** [comment]
How does possible please describe we use this in my website 
www.hotsprice.com
